## server config
server:
  port: 8080

## driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/animaldb
    username: animal
    password: animal
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true

#  mvc:
#    static-path-pattern: /static/**

## mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
